#!/bin/bash
#SBATCH --job-name=kraken2_batch
#SBATCH --output=/home/yc1201/final_project/kraken2/kraken2-%j.out
#SBATCH --error=/home/yc1201/final_project//kraken2/kraken2-%j.err
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=yc1201@georgetown.edu
#SBATCH --time=12:00:00
#SBATCH --mem=128G
#SBATCH --cpus-per-task=8

set -euo pipefail

# --------- PATHS ----------
DB="/home/yc1201/final_project/kraken2"   # where hash.k2d etc. are
READDIR="/home/yc1201/final_project/bowtie"
OUTDIR="/home/yc1201/final_project/kraken2"

# --------- LOAD ENV ----------
source /home/share/apps/python/anaconda3-3.13/bin/activate kraken_env

# --------- SETUP OUTPUT ----------
mkdir -p "${OUTDIR}"
cd "${OUTDIR}"

echo "Starting Kraken2 runs"

# --------- SAMPLE 1 ----------
echo "Running sample: S13_350"

kraken2 \
  --db "${DB}" \
  --paired \
  --threads 8 \
  --use-names \
  --report S13_350.report \
  --output S13_350.kraken \
  "${READDIR}/S13_350_nonhuman_R1.fq.gz" \
  "${READDIR}/S13_350_nonhuman_R2.fq.gz"

echo "Finished S13_350"

# --------- SAMPLE 2 ----------
echo "Running sample: S9_350_1"

kraken2 \
  --db "${DB}" \
  --db "${DB}" \
  --paired \
  --threads 8 \
  --use-names \
  --report S9_350_1.report \
  --output S9_350_1.kraken \
  "${READDIR}/S9_350_1_nonhuman_R1.fq.gz" \
  "${READDIR}/S9_350_1_nonhuman_R2.fq.gz"

echo "Finished S9_350_1"

echo "All Kraken2 runs completed"


